=== ryn-cx/yt-dlapi/src/yt_dlapi/channel/models.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"id": {"type": "string"}, "channel": {"type": "string"}, "channel_id": {"type": "string"}, "title": {"type": "string"}, "availability": {"type": "null"}, "channel_follower_count": {"type": "integer"}, "description": {"type": "string"}, "tags": {"type": "array", "items": {"type": "string"}}, "thumbnails": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "height": {"type": "integer"}, "width": {"type": "integer"}, "id": {"type": "string"}, "preference": {"type": "integer"}}, "required": ["url"]}}, "uploader_id": {"type": "string"}, "uploader_url": {"type": "string"}, "modified_date": {"type": "null"}, "view_count": {"type": "null"}, "playlist_count": {"type": "null"}, "uploader": {"type": "string"}, "channel_url": {"type": "string"}, "_type": {"type": "string"}, "entries": {"type": "string"}, "extractor_key": {"type": "string"}, "extractor": {"type": "string"}, "webpage_url": {"type": "string"}, "original_url": {"type": "string"}, "webpage_url_basename": {"type": "string"}, "webpage_url_domain": {"type": "string"}, "epoch": {"type": "integer"}, "_version": {"type": "object", "properties": {"version": {"type": "string"}, "current_git_head": {"type": "null"}, "release_git_head": {"type": "string"}, "repository": {"type": "string"}}, "required": ["current_git_head", "release_git_head", "repository", "version"]}, "yt_dlapi": {"type": "object", "properties": {"timestamp": {"format": "date-time", "type": "string"}, "url": {"type": "string"}, "params": {"type": "object", "properties": {"extract_flat": {"type": "boolean"}, "process": {"type": "boolean"}}, "required": ["extract_flat", "process"]}}, "required": ["params", "timestamp", "url"]}}, "required": ["_type", "_version", "availability", "channel", "channel_follower_count", "channel_id", "channel_url", "description", "entries", "epoch", "extractor", "extractor_key", "id", "modified_date", "original_url", "playlist_count", "tags", "thumbnails", "title", "uploader", "uploader_id", "uploader_url", "view_count", "webpage_url", "webpage_url_basename", "webpage_url_domain"]}

=== ryn-cx/yt-dlapi/src/yt_dlapi/_input/channel/fc6190d4-37ad-4deb-8e13-892b39e6ee2a.json
{
  "id": "UC4QobU6STFB0P71PMvOGN5A",
  "channel": "jawed",
  "channel_id": "UC4QobU6STFB0P71PMvOGN5A",
  "title": "jawed - Videos",
  "availability": null,
  "channel_follower_count": 5720000,
  "description": "",
  "tags": [
    "me at the zoo",
    "jawed karim",
    "first youtube video"
  ],
  "thumbnails": [
    {
      "url": "https://yt3.googleusercontent.com/uI3VE4PVqvCy0xnWLqMJnEzyBUm3T8VHOCp4ee-1RxdHqKXCdUE_qXYQnpf9AfuEoIPactVyDhM=s900-c-k-c0x00ffffff-no-rj",
      "height": 900,
      "width": 900
    },
    {
      "url": "https://yt3.googleusercontent.com/uI3VE4PVqvCy0xnWLqMJnEzyBUm3T8VHOCp4ee-1RxdHqKXCdUE_qXYQnpf9AfuEoIPactVyDhM=s0",
      "id": "avatar_uncropped",
      "preference": 1
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w1060-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 175,
      "width": 1060,
      "preference": -10
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w1138-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 188,
      "width": 1138,
      "preference": -10
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 283,
      "width": 1707,
      "preference": -10
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 351,
      "width": 2120,
      "preference": -10
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w2276-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 377,
      "width": 2276,
      "preference": -10
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w2560-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 424,
      "width": 2560,
      "preference": -10
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=s0",
      "id": "banner_uncropped",
      "preference": -5
    }
  ],
  "uploader_id": "@jawed",
  "uploader_url": "https://www.youtube.com/@jawed",
  "modified_date": null,
  "view_count": null,
  "playlist_count": null,
  "uploader": "jawed",
  "channel_url": "https://www.youtube.com/channel/UC4QobU6STFB0P71PMvOGN5A",
  "_type": "playlist",
  "entries": "<generator object YoutubeTabBaseInfoExtractor._entries at 0x000002290C3472E0>",
  "extractor_key": "YoutubeTab",
  "extractor": "youtube:tab",
  "webpage_url": "https://www.youtube.com/jawed/videos",
  "original_url": "https://www.youtube.com/jawed",
  "webpage_url_basename": "videos",
  "webpage_url_domain": "youtube.com",
  "epoch": 1758977383,
  "_version": {
    "version": "2025.09.26",
    "current_git_head": null,
    "release_git_head": "12b57d2858845c0c7fb33bf9aa8ed7be6905535d",
    "repository": "yt-dlp/yt-dlp"
  }
}
