=== ryn-cx/yt-dlapi/src/yt_dlapi/channel/schema.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"id": {"type": "string"}, "channel": {"type": "string"}, "channel_id": {"type": "string"}, "title": {"type": "string"}, "availability": {"type": "null"}, "channel_follower_count": {"type": "integer"}, "description": {"type": "string"}, "tags": {"type": "array", "items": {"type": "string"}}, "thumbnails": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "height": {"type": "integer"}, "width": {"type": "integer"}, "preference": {"type": "integer"}, "id": {"type": "string"}, "resolution": {"type": "string"}}, "required": ["id", "url"]}}, "uploader_id": {"type": "string"}, "uploader_url": {"type": "string"}, "modified_date": {"type": "null"}, "view_count": {"type": "null"}, "playlist_count": {"type": "integer"}, "uploader": {"type": "string"}, "channel_url": {"type": "string"}, "_type": {"type": "string"}, "entries": {"type": "array", "items": {"type": "object", "properties": {"id": {"type": "string"}, "channel": {"type": ["null", "string"]}, "channel_id": {"type": ["null", "string"]}, "title": {"type": "string"}, "availability": {"type": "null"}, "channel_follower_count": {"type": "integer"}, "description": {"type": ["null", "string"]}, "tags": {"type": "array", "items": {"type": "string"}}, "thumbnails": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "height": {"type": "integer"}, "width": {"type": "integer"}, "preference": {"type": "integer"}, "id": {"type": "string"}, "resolution": {"type": "string"}}, "required": ["url"]}}, "uploader_id": {"type": ["null", "string"]}, "uploader_url": {"type": ["null", "string"]}, "modified_date": {"type": "null"}, "view_count": {"type": ["integer", "null"]}, "playlist_count": {"type": "integer"}, "uploader": {"type": ["null", "string"]}, "channel_url": {"type": ["null", "string"]}, "_type": {"type": "string"}, "entries": {"type": "array", "items": {"type": "object", "properties": {"_type": {"type": "string"}, "ie_key": {"type": "string"}, "id": {"type": "string"}, "url": {"type": "string"}, "title": {"type": "string"}, "description": {"type": ["null", "string"]}, "duration": {"type": "number"}, "channel_id": {"type": "null"}, "channel": {"type": ["null", "string"]}, "channel_url": {"type": "null"}, "uploader": {"type": ["null", "string"]}, "uploader_id": {"type": "null"}, "uploader_url": {"type": "null"}, "thumbnails": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "height": {"type": "integer"}, "width": {"type": "integer"}}, "required": ["height", "url", "width"]}}, "timestamp": {"type": "null"}, "release_timestamp": {"type": "null"}, "availability": {"type": ["null", "string"]}, "view_count": {"type": ["integer", "null"]}, "live_status": {"type": ["null", "string"]}, "channel_is_verified": {"type": ["boolean", "null"]}, "__x_forwarded_for_ip": {"type": "null"}}, "required": ["__x_forwarded_for_ip", "_type", "id", "ie_key", "thumbnails", "title", "url", "view_count"]}}, "extractor_key": {"type": "string"}, "extractor": {"type": "string"}, "webpage_url": {"type": "string"}, "__x_forwarded_for_ip": {"type": "null"}, "release_year": {"type": "null"}, "epoch": {"type": "integer"}, "ie_key": {"type": "string"}, "url": {"type": "string"}, "duration": {"type": "number"}, "timestamp": {"type": "null"}, "release_timestamp": {"type": "null"}, "live_status": {"type": "null"}, "channel_is_verified": {"type": "boolean"}}, "required": ["__x_forwarded_for_ip", "_type", "availability", "channel", "channel_id", "channel_url", "description", "id", "thumbnails", "title", "uploader", "uploader_id", "uploader_url", "view_count"]}}, "webpage_url": {"type": "string"}, "original_url": {"type": "string"}, "webpage_url_basename": {"type": "string"}, "webpage_url_domain": {"type": "string"}, "extractor": {"type": "string"}, "extractor_key": {"type": "string"}, "release_year": {"type": "null"}, "epoch": {"type": "integer"}, "_version": {"type": "object", "properties": {"version": {"type": "string"}, "current_git_head": {"type": "null"}, "release_git_head": {"type": "string"}, "repository": {"type": "string"}}, "required": ["current_git_head", "release_git_head", "repository", "version"]}}, "required": ["_type", "_version", "availability", "channel", "channel_follower_count", "channel_id", "channel_url", "description", "entries", "epoch", "extractor", "extractor_key", "id", "modified_date", "original_url", "playlist_count", "release_year", "tags", "thumbnails", "title", "uploader", "uploader_id", "uploader_url", "view_count", "webpage_url", "webpage_url_basename", "webpage_url_domain"]}

=== ryn-cx/yt-dlapi/src/yt_dlapi/_input/channel/e158e486-558c-404a-aaca-b14654a235f1.json
{
  "id": "UC4QobU6STFB0P71PMvOGN5A",
  "channel": "jawed",
  "channel_id": "UC4QobU6STFB0P71PMvOGN5A",
  "title": "jawed - Videos",
  "availability": null,
  "channel_follower_count": 5720000,
  "description": "",
  "tags": [
    "me at the zoo",
    "jawed karim",
    "first youtube video"
  ],
  "thumbnails": [
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w1060-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 175,
      "width": 1060,
      "preference": -10,
      "id": "0",
      "resolution": "1060x175"
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w1138-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 188,
      "width": 1138,
      "preference": -10,
      "id": "1",
      "resolution": "1138x188"
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 283,
      "width": 1707,
      "preference": -10,
      "id": "2",
      "resolution": "1707x283"
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 351,
      "width": 2120,
      "preference": -10,
      "id": "3",
      "resolution": "2120x351"
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w2276-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 377,
      "width": 2276,
      "preference": -10,
      "id": "4",
      "resolution": "2276x377"
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=w2560-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj",
      "height": 424,
      "width": 2560,
      "preference": -10,
      "id": "5",
      "resolution": "2560x424"
    },
    {
      "url": "https://yt3.googleusercontent.com/9oxdo7zGCuEofTfnBIuUAf7B0ynncs-aQmgx9lXQ33VRwrJyQlHmYpH6wfczKgGYfVThQ31dhg=s0",
      "id": "banner_uncropped",
      "preference": -5
    },
    {
      "url": "https://yt3.googleusercontent.com/uI3VE4PVqvCy0xnWLqMJnEzyBUm3T8VHOCp4ee-1RxdHqKXCdUE_qXYQnpf9AfuEoIPactVyDhM=s900-c-k-c0x00ffffff-no-rj",
      "height": 900,
      "width": 900,
      "id": "7",
      "resolution": "900x900"
    },
    {
      "url": "https://yt3.googleusercontent.com/uI3VE4PVqvCy0xnWLqMJnEzyBUm3T8VHOCp4ee-1RxdHqKXCdUE_qXYQnpf9AfuEoIPactVyDhM=s0",
      "id": "avatar_uncropped",
      "preference": 1
    }
  ],
  "uploader_id": "@jawed",
  "uploader_url": "https://www.youtube.com/@jawed",
  "modified_date": null,
  "view_count": null,
  "playlist_count": 1,
  "uploader": "jawed",
  "channel_url": "https://www.youtube.com/channel/UC4QobU6STFB0P71PMvOGN5A",
  "_type": "playlist",
  "entries": [
    {
      "_type": "url",
      "ie_key": "Youtube",
      "id": "jNQXAC9IVRw",
      "url": "https://www.youtube.com/watch?v=jNQXAC9IVRw",
      "title": "Me at the zoo",
      "description": "Microplastics are accumulating in human brains at an alarming rate\nhttps://www.youtube.com/watch?v=0PT5c1z3LL8\n\n\u201cNanoplastics and Human Health\u201d with Matthew J Campen, PhD, MSPH\nhttps://www.yout...",
      "duration": 19.0,
      "channel_id": null,
      "channel": null,
      "channel_url": null,
      "uploader": null,
      "uploader_id": null,
      "uploader_url": null,
      "thumbnails": [
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE1CKgBEF5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AG-AoAC8AGKAgwIABABGFUgWShlMA8=&rs=AOn4CLD0z8RhQhBpOGg7rE1WwNmsXhJviQ",
          "height": 94,
          "width": 168
        },
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE1CMQBEG5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AG-AoAC8AGKAgwIABABGFUgWShlMA8=&rs=AOn4CLDEByjISd3w-TM9Pzzz3rxWDxLQNw",
          "height": 110,
          "width": 196
        },
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE2CPYBEIoBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgBvgKAAvABigIMCAAQARhVIFkoZTAP&rs=AOn4CLAtWrYHlO_zHK-I-52tzA86tqSeAw",
          "height": 138,
          "width": 246
        },
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgBvgKAAvABigIMCAAQARhVIFkoZTAP&rs=AOn4CLB7NY0fx4yZYDj27223V3b7Sowf5w",
          "height": 188,
          "width": 336
        }
      ],
      "timestamp": null,
      "release_timestamp": null,
      "availability": null,
      "view_count": 372395946,
      "live_status": null,
      "channel_is_verified": true,
      "__x_forwarded_for_ip": null
    }
  ],
  "extractor_key": "YoutubeTab",
  "extractor": "youtube:tab",
  "webpage_url": "https://www.youtube.com/jawed/videos",
  "original_url": "https://www.youtube.com/jawed",
  "webpage_url_basename": "videos",
  "webpage_url_domain": "youtube.com",
  "release_year": null,
  "epoch": 1758953505,
  "_version": {
    "version": "2025.09.26",
    "current_git_head": null,
    "release_git_head": "12b57d2858845c0c7fb33bf9aa8ed7be6905535d",
    "repository": "yt-dlp/yt-dlp"
  }
}
