=== ryn-cx/yt-dlapi/src/yt_dlapi/playlist/models.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"id": {"type": "string"}, "title": {"type": "string"}, "availability": {"type": "null"}, "channel_follower_count": {"type": "null"}, "description": {"type": "string"}, "tags": {"type": "array"}, "thumbnails": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "height": {"type": "integer"}, "width": {"type": "integer"}}, "required": ["height", "url", "width"]}}, "modified_date": {"type": "string"}, "view_count": {"type": "integer"}, "playlist_count": {"type": "integer"}, "channel": {"type": "string"}, "channel_id": {"type": "string"}, "uploader_id": {"type": "string"}, "uploader": {"type": "string"}, "channel_url": {"type": "string"}, "uploader_url": {"type": "string"}, "_type": {"type": "string"}, "entries": {"type": "string"}, "extractor_key": {"type": "string"}, "extractor": {"type": "string"}, "webpage_url": {"type": "string"}, "original_url": {"type": "string"}, "webpage_url_basename": {"type": "string"}, "webpage_url_domain": {"type": "string"}, "epoch": {"type": "integer"}, "_version": {"type": "object", "properties": {"version": {"type": "string"}, "current_git_head": {"type": "null"}, "release_git_head": {"type": "string"}, "repository": {"type": "string"}}, "required": ["current_git_head", "release_git_head", "repository", "version"]}, "yt_dlapi": {"type": "object", "properties": {"timestamp": {"format": "date-time", "type": "string"}, "url": {"type": "string"}, "params": {"type": "object", "properties": {"extract_flat": {"type": "boolean"}, "process": {"type": "boolean"}}, "required": ["extract_flat", "process"]}}, "required": ["params", "timestamp", "url"]}}, "required": ["_type", "_version", "availability", "channel", "channel_follower_count", "channel_id", "channel_url", "description", "entries", "epoch", "extractor", "extractor_key", "id", "modified_date", "original_url", "playlist_count", "tags", "thumbnails", "title", "uploader", "uploader_id", "uploader_url", "view_count", "webpage_url", "webpage_url_basename", "webpage_url_domain"]}

=== ryn-cx/yt-dlapi/src/yt_dlapi/_input/playlist/742ca00f-4453-408b-befe-be9220a5b905.json
{
  "id": "PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh",
  "title": "YouTube",
  "availability": null,
  "channel_follower_count": null,
  "description": "",
  "tags": [],
  "thumbnails": [
    {
      "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEWCKgBEF5IWvKriqkDCQgBFQAAiEIYAQ==&rs=AOn4CLDSFko5GVHTf22FMkOm4uTb-Pf9Dg",
      "height": 94,
      "width": 168
    },
    {
      "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEWCMQBEG5IWvKriqkDCQgBFQAAiEIYAQ==&rs=AOn4CLA8f0t8tVMqcdG1QYuh-sQ9Uc53jg",
      "height": 110,
      "width": 196
    },
    {
      "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEXCPYBEIoBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBWhQYFRuvG9dqKU87pDh_sIjnRUw",
      "height": 138,
      "width": 246
    },
    {
      "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC4pN2ks4OQluY83-zIqMilztBF5A",
      "height": 188,
      "width": 336
    }
  ],
  "modified_date": "20250123",
  "view_count": 7844062,
  "playlist_count": 4,
  "channel": "jawed",
  "channel_id": "UC4QobU6STFB0P71PMvOGN5A",
  "uploader_id": "@jawed",
  "uploader": "jawed",
  "channel_url": "https://www.youtube.com/channel/UC4QobU6STFB0P71PMvOGN5A",
  "uploader_url": "https://www.youtube.com/@jawed",
  "_type": "playlist",
  "entries": "<generator object YoutubeTabBaseInfoExtractor._entries at 0x00000243AE8976A0>",
  "extractor_key": "YoutubeTab",
  "extractor": "youtube:tab",
  "webpage_url": "https://www.youtube.com/playlist?list=PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh",
  "original_url": "https://www.youtube.com/playlist?list=PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh",
  "webpage_url_basename": "playlist",
  "webpage_url_domain": "youtube.com",
  "epoch": 1758977914,
  "_version": {
    "version": "2025.09.26",
    "current_git_head": null,
    "release_git_head": "12b57d2858845c0c7fb33bf9aa8ed7be6905535d",
    "repository": "yt-dlp/yt-dlp"
  }
}

=== ryn-cx/yt-dlapi/src/yt_dlapi/_input/playlist/f77649c5-7e70-4fb1-9884-342e928cdeff.json
{
  "id": "UU4QobU6STFB0P71PMvOGN5A",
  "title": "Uploads from jawed",
  "availability": "public",
  "channel_follower_count": null,
  "description": "",
  "tags": [],
  "thumbnails": [
    {
      "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwEwCKgBEF5IWvKriqkDIwgBFQAAiEIYAfABAfgBvgKAAvABigIMCAAQARhVIFkoZTAP&rs=AOn4CLDrlUsFyWeYqxx-GVhoVmyrdLX1Mw",
      "height": 94,
      "width": 168
    },
    {
      "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwEwCMQBEG5IWvKriqkDIwgBFQAAiEIYAfABAfgBvgKAAvABigIMCAAQARhVIFkoZTAP&rs=AOn4CLDw3_tnaIJlqTOXjPNNa0GCPb-hkw",
      "height": 110,
      "width": 196
    },
    {
      "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwExCPYBEIoBSFryq4qpAyMIARUAAIhCGAHwAQH4Ab4CgALwAYoCDAgAEAEYVSBZKGUwDw==&rs=AOn4CLBjDqag9EZyWMs56tG_EynO13cihQ",
      "height": 138,
      "width": 246
    },
    {
      "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwExCNACELwBSFryq4qpAyMIARUAAIhCGAHwAQH4Ab4CgALwAYoCDAgAEAEYVSBZKGUwDw==&rs=AOn4CLBup3YZ8rAcAVSV0yok3hVVe4lErA",
      "height": 188,
      "width": 336
    }
  ],
  "modified_date": "20240717",
  "view_count": 497723,
  "playlist_count": 1,
  "channel": "jawed",
  "channel_id": "UC4QobU6STFB0P71PMvOGN5A",
  "uploader_id": "@jawed",
  "uploader": "jawed",
  "channel_url": "https://www.youtube.com/channel/UC4QobU6STFB0P71PMvOGN5A",
  "uploader_url": "https://www.youtube.com/@jawed",
  "_type": "playlist",
  "entries": "<generator object YoutubeTabBaseInfoExtractor._entries at 0x0000019B43644D60>",
  "extractor_key": "YoutubeTab",
  "extractor": "youtube:tab",
  "webpage_url": "https://www.youtube.com/playlist?list=UU4QobU6STFB0P71PMvOGN5A",
  "original_url": "https://www.youtube.com/playlist?list=UU4QobU6STFB0P71PMvOGN5A",
  "webpage_url_basename": "playlist",
  "webpage_url_domain": "youtube.com",
  "epoch": 1758980722,
  "_version": {
    "version": "2025.09.26",
    "current_git_head": null,
    "release_git_head": "12b57d2858845c0c7fb33bf9aa8ed7be6905535d",
    "repository": "yt-dlp/yt-dlp"
  }
}
