=== ryn-cx/yt-dlapi/src/yt_dlapi/playlist/schema.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"id": {"type": "string"}, "title": {"type": "string"}, "availability": {"type": "null"}, "channel_follower_count": {"type": "null"}, "description": {"type": "string"}, "tags": {"type": "array"}, "thumbnails": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "height": {"type": "integer"}, "width": {"type": "integer"}, "id": {"type": "string"}, "resolution": {"type": "string"}}, "required": ["height", "id", "resolution", "url", "width"]}}, "modified_date": {"type": "string"}, "view_count": {"type": "integer"}, "playlist_count": {"type": "integer"}, "channel": {"type": "string"}, "channel_id": {"type": "string"}, "uploader_id": {"type": "string"}, "uploader": {"type": "string"}, "channel_url": {"type": "string"}, "uploader_url": {"type": "string"}, "_type": {"type": "string"}, "entries": {"type": "array", "items": {"type": "object", "properties": {"_type": {"type": "string"}, "ie_key": {"type": "string"}, "id": {"type": "string"}, "url": {"type": "string"}, "title": {"type": "string"}, "description": {"type": "null"}, "duration": {"type": "integer"}, "channel_id": {"type": ["null", "string"]}, "channel": {"type": "string"}, "channel_url": {"type": ["null", "string"]}, "uploader": {"type": "string"}, "uploader_id": {"type": ["null", "string"]}, "uploader_url": {"type": ["null", "string"]}, "thumbnails": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "height": {"type": "integer"}, "width": {"type": "integer"}}, "required": ["height", "url", "width"]}}, "timestamp": {"type": "null"}, "release_timestamp": {"type": "null"}, "availability": {"type": "null"}, "view_count": {"type": "integer"}, "live_status": {"type": ["null", "string"]}, "channel_is_verified": {"type": "null"}, "__x_forwarded_for_ip": {"type": "null"}}, "required": ["__x_forwarded_for_ip", "_type", "availability", "channel", "channel_id", "channel_is_verified", "channel_url", "description", "duration", "id", "ie_key", "live_status", "release_timestamp", "thumbnails", "timestamp", "title", "uploader", "uploader_id", "uploader_url", "url", "view_count"]}}, "extractor_key": {"type": "string"}, "extractor": {"type": "string"}, "webpage_url": {"type": "string"}, "original_url": {"type": "string"}, "webpage_url_basename": {"type": "string"}, "webpage_url_domain": {"type": "string"}, "release_year": {"type": "null"}, "epoch": {"type": "integer"}, "_version": {"type": "object", "properties": {"version": {"type": "string"}, "current_git_head": {"type": "null"}, "release_git_head": {"type": "string"}, "repository": {"type": "string"}}, "required": ["current_git_head", "release_git_head", "repository", "version"]}}, "required": ["_type", "_version", "availability", "channel", "channel_follower_count", "channel_id", "channel_url", "description", "entries", "epoch", "extractor", "extractor_key", "id", "modified_date", "original_url", "playlist_count", "release_year", "tags", "thumbnails", "title", "uploader", "uploader_id", "uploader_url", "view_count", "webpage_url", "webpage_url_basename", "webpage_url_domain"]}

=== ryn-cx/yt-dlapi/src/yt_dlapi/_input/playlist_videos/93292150-45f3-4397-a598-e3880d13808a.json
{
  "id": "PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh",
  "title": "YouTube",
  "availability": null,
  "channel_follower_count": null,
  "description": "",
  "tags": [],
  "thumbnails": [
    {
      "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEWCKgBEF5IWvKriqkDCQgBFQAAiEIYAQ==&rs=AOn4CLDSFko5GVHTf22FMkOm4uTb-Pf9Dg",
      "height": 94,
      "width": 168,
      "id": "0",
      "resolution": "168x94"
    },
    {
      "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEWCMQBEG5IWvKriqkDCQgBFQAAiEIYAQ==&rs=AOn4CLA8f0t8tVMqcdG1QYuh-sQ9Uc53jg",
      "height": 110,
      "width": 196,
      "id": "1",
      "resolution": "196x110"
    },
    {
      "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEXCPYBEIoBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBWhQYFRuvG9dqKU87pDh_sIjnRUw",
      "height": 138,
      "width": 246,
      "id": "2",
      "resolution": "246x138"
    },
    {
      "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC4pN2ks4OQluY83-zIqMilztBF5A",
      "height": 188,
      "width": 336,
      "id": "3",
      "resolution": "336x188"
    }
  ],
  "modified_date": "20250123",
  "view_count": 7844062,
  "playlist_count": 4,
  "channel": "jawed",
  "channel_id": "UC4QobU6STFB0P71PMvOGN5A",
  "uploader_id": "@jawed",
  "uploader": "jawed",
  "channel_url": "https://www.youtube.com/channel/UC4QobU6STFB0P71PMvOGN5A",
  "uploader_url": "https://www.youtube.com/@jawed",
  "_type": "playlist",
  "entries": [
    {
      "_type": "url",
      "ie_key": "Youtube",
      "id": "lVI_J1cbFb4",
      "url": "https://www.youtube.com/watch?v=lVI_J1cbFb4",
      "title": "How YouTube Was Created ft. Founder Steve Chen",
      "description": null,
      "duration": 2895,
      "channel_id": "UCWrF0oN6unbXrWsTN7RctTw",
      "channel": "Sequoia Capital",
      "channel_url": "https://www.youtube.com/channel/UCWrF0oN6unbXrWsTN7RctTw",
      "uploader": "Sequoia Capital",
      "uploader_id": "@sequoiacapital",
      "uploader_url": "https://www.youtube.com/@sequoiacapital",
      "thumbnails": [
        {
          "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDg-TUHZ1M57zW4yQ5XtpIkLSspsQ",
          "height": 94,
          "width": 168
        },
        {
          "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAQqo8tz0lptrtqU6FQeYGR2yNi5w",
          "height": 110,
          "width": 196
        },
        {
          "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLANNaFpdfytCqFtSPAyfU_YzzV8KA",
          "height": 138,
          "width": 246
        },
        {
          "url": "https://i.ytimg.com/vi/lVI_J1cbFb4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBS8Rt30uwZpg7uFmq_rJHjn6t69A",
          "height": 188,
          "width": 336
        }
      ],
      "timestamp": null,
      "release_timestamp": null,
      "availability": null,
      "view_count": 305000,
      "live_status": null,
      "channel_is_verified": null,
      "__x_forwarded_for_ip": null
    },
    {
      "_type": "url",
      "ie_key": "Youtube",
      "id": "XAJEXUNmP5M",
      "url": "https://www.youtube.com/watch?v=XAJEXUNmP5M",
      "title": "r | p 2006: YouTube: From Concept to Hypergrowth - Jawed Karim",
      "description": null,
      "duration": 3049,
      "channel_id": "UCm5h-rixlNgYL1PoFPJjYog",
      "channel": "Reflections Projections",
      "channel_url": "https://www.youtube.com/channel/UCm5h-rixlNgYL1PoFPJjYog",
      "uploader": "Reflections Projections",
      "uploader_id": "@acmuiuc",
      "uploader_url": "https://www.youtube.com/@acmuiuc",
      "thumbnails": [
        {
          "url": "https://i.ytimg.com/vi/XAJEXUNmP5M/hqdefault.jpg?sqp=-oaymwE1CKgBEF5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AG-B4AC0AWKAgwIABABGE8gXihlMA8=&rs=AOn4CLDCZ6PFWLMJ-4V8ektPqDmFuoOIcw",
          "height": 94,
          "width": 168
        },
        {
          "url": "https://i.ytimg.com/vi/XAJEXUNmP5M/hqdefault.jpg?sqp=-oaymwE1CMQBEG5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AG-B4AC0AWKAgwIABABGE8gXihlMA8=&rs=AOn4CLCewS2aaBqlc0_9pFDMlouysn0tjw",
          "height": 110,
          "width": 196
        },
        {
          "url": "https://i.ytimg.com/vi/XAJEXUNmP5M/hqdefault.jpg?sqp=-oaymwE2CPYBEIoBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgBvgeAAtAFigIMCAAQARhPIF4oZTAP&rs=AOn4CLCOhCTYN_lk033itWQokJxiGrcQDQ",
          "height": 138,
          "width": 246
        },
        {
          "url": "https://i.ytimg.com/vi/XAJEXUNmP5M/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgBvgeAAtAFigIMCAAQARhPIF4oZTAP&rs=AOn4CLAB-slQi_iURBHdGWi87fFlOCzHSA",
          "height": 188,
          "width": 336
        }
      ],
      "timestamp": null,
      "release_timestamp": null,
      "availability": null,
      "view_count": 6600000,
      "live_status": null,
      "channel_is_verified": null,
      "__x_forwarded_for_ip": null
    },
    {
      "_type": "url",
      "ie_key": "Youtube",
      "id": "VaLXzI92t9M",
      "url": "https://www.youtube.com/watch?v=VaLXzI92t9M",
      "title": "First Back Flip on Youtube! (House dismount) #2005  #viralvideo",
      "description": null,
      "duration": 61,
      "channel_id": "UCs0ACZIa1m4ecu2zijr-8Sg",
      "channel": "COBALTGRUV",
      "channel_url": "https://www.youtube.com/channel/UCs0ACZIa1m4ecu2zijr-8Sg",
      "uploader": "COBALTGRUV",
      "uploader_id": "@COBALTGRUV",
      "uploader_url": "https://www.youtube.com/@COBALTGRUV",
      "thumbnails": [
        {
          "url": "https://i.ytimg.com/vi/VaLXzI92t9M/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA0vbWeThYpPda1bvQtrfcIgXdPYQ",
          "height": 94,
          "width": 168
        },
        {
          "url": "https://i.ytimg.com/vi/VaLXzI92t9M/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBi0D0OWf9ORAfZ4XEmWpKQ2Nwuag",
          "height": 110,
          "width": 196
        },
        {
          "url": "https://i.ytimg.com/vi/VaLXzI92t9M/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAt7osjLTP9J-M9NN-MvXXfGBTudA",
          "height": 138,
          "width": 246
        },
        {
          "url": "https://i.ytimg.com/vi/VaLXzI92t9M/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDL4KEueNjQfyTGtvWGM5nJIQc6Dw",
          "height": 188,
          "width": 336
        }
      ],
      "timestamp": null,
      "release_timestamp": null,
      "availability": null,
      "view_count": 3700000,
      "live_status": null,
      "channel_is_verified": null,
      "__x_forwarded_for_ip": null
    },
    {
      "_type": "url",
      "ie_key": "Youtube",
      "id": "jNQXAC9IVRw",
      "url": "https://www.youtube.com/watch?v=jNQXAC9IVRw",
      "title": "Me at the zoo",
      "description": null,
      "duration": 19,
      "channel_id": "UC4QobU6STFB0P71PMvOGN5A",
      "channel": "jawed",
      "channel_url": "https://www.youtube.com/channel/UC4QobU6STFB0P71PMvOGN5A",
      "uploader": "jawed",
      "uploader_id": "@jawed",
      "uploader_url": "https://www.youtube.com/@jawed",
      "thumbnails": [
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE1CKgBEF5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AG-AoAC8AGKAgwIABABGFUgWShlMA8=&rs=AOn4CLD0z8RhQhBpOGg7rE1WwNmsXhJviQ",
          "height": 94,
          "width": 168
        },
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE1CMQBEG5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AG-AoAC8AGKAgwIABABGFUgWShlMA8=&rs=AOn4CLDEByjISd3w-TM9Pzzz3rxWDxLQNw",
          "height": 110,
          "width": 196
        },
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE2CPYBEIoBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgBvgKAAvABigIMCAAQARhVIFkoZTAP&rs=AOn4CLAtWrYHlO_zHK-I-52tzA86tqSeAw",
          "height": 138,
          "width": 246
        },
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgBvgKAAvABigIMCAAQARhVIFkoZTAP&rs=AOn4CLB7NY0fx4yZYDj27223V3b7Sowf5w",
          "height": 188,
          "width": 336
        }
      ],
      "timestamp": null,
      "release_timestamp": null,
      "availability": null,
      "view_count": 372000000,
      "live_status": null,
      "channel_is_verified": null,
      "__x_forwarded_for_ip": null
    }
  ],
  "extractor_key": "YoutubeTab",
  "extractor": "youtube:tab",
  "webpage_url": "https://www.youtube.com/playlist?list=PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh",
  "original_url": "https://www.youtube.com/playlist?list=PLuhl9TnQPDCnWIhy_KSbtFwXVQnNvgfSh",
  "webpage_url_basename": "playlist",
  "webpage_url_domain": "youtube.com",
  "release_year": null,
  "epoch": 1758977752,
  "_version": {
    "version": "2025.09.26",
    "current_git_head": null,
    "release_git_head": "12b57d2858845c0c7fb33bf9aa8ed7be6905535d",
    "repository": "yt-dlp/yt-dlp"
  }
}

=== ryn-cx/yt-dlapi/src/yt_dlapi/_input/playlist_videos/e67eb9f6-7d35-4e23-a837-5f43508d7971.json
{
  "id": "UU4QobU6STFB0P71PMvOGN5A",
  "title": "Uploads from jawed",
  "availability": "public",
  "channel_follower_count": null,
  "description": "",
  "tags": [],
  "thumbnails": [
    {
      "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwEwCKgBEF5IWvKriqkDIwgBFQAAiEIYAfABAfgBvgKAAvABigIMCAAQARhVIFkoZTAP&rs=AOn4CLDrlUsFyWeYqxx-GVhoVmyrdLX1Mw",
      "height": 94,
      "width": 168,
      "id": "0",
      "resolution": "168x94"
    },
    {
      "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwEwCMQBEG5IWvKriqkDIwgBFQAAiEIYAfABAfgBvgKAAvABigIMCAAQARhVIFkoZTAP&rs=AOn4CLDw3_tnaIJlqTOXjPNNa0GCPb-hkw",
      "height": 110,
      "width": 196,
      "id": "1",
      "resolution": "196x110"
    },
    {
      "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwExCPYBEIoBSFryq4qpAyMIARUAAIhCGAHwAQH4Ab4CgALwAYoCDAgAEAEYVSBZKGUwDw==&rs=AOn4CLBjDqag9EZyWMs56tG_EynO13cihQ",
      "height": 138,
      "width": 246,
      "id": "2",
      "resolution": "246x138"
    },
    {
      "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwExCNACELwBSFryq4qpAyMIARUAAIhCGAHwAQH4Ab4CgALwAYoCDAgAEAEYVSBZKGUwDw==&rs=AOn4CLBup3YZ8rAcAVSV0yok3hVVe4lErA",
      "height": 188,
      "width": 336,
      "id": "3",
      "resolution": "336x188"
    }
  ],
  "modified_date": "20240717",
  "view_count": 497723,
  "playlist_count": 1,
  "channel": "jawed",
  "channel_id": "UC4QobU6STFB0P71PMvOGN5A",
  "uploader_id": "@jawed",
  "uploader": "jawed",
  "channel_url": "https://www.youtube.com/channel/UC4QobU6STFB0P71PMvOGN5A",
  "uploader_url": "https://www.youtube.com/@jawed",
  "_type": "playlist",
  "entries": [
    {
      "_type": "url",
      "ie_key": "Youtube",
      "id": "jNQXAC9IVRw",
      "url": "https://www.youtube.com/watch?v=jNQXAC9IVRw",
      "title": "Me at the zoo",
      "description": null,
      "duration": 19,
      "channel_id": "UC4QobU6STFB0P71PMvOGN5A",
      "channel": "jawed",
      "channel_url": "https://www.youtube.com/channel/UC4QobU6STFB0P71PMvOGN5A",
      "uploader": "jawed",
      "uploader_id": "@jawed",
      "uploader_url": "https://www.youtube.com/@jawed",
      "thumbnails": [
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE1CKgBEF5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AG-AoAC8AGKAgwIABABGFUgWShlMA8=&rs=AOn4CLD0z8RhQhBpOGg7rE1WwNmsXhJviQ",
          "height": 94,
          "width": 168
        },
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE1CMQBEG5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AG-AoAC8AGKAgwIABABGFUgWShlMA8=&rs=AOn4CLDEByjISd3w-TM9Pzzz3rxWDxLQNw",
          "height": 110,
          "width": 196
        },
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE2CPYBEIoBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgBvgKAAvABigIMCAAQARhVIFkoZTAP&rs=AOn4CLAtWrYHlO_zHK-I-52tzA86tqSeAw",
          "height": 138,
          "width": 246
        },
        {
          "url": "https://i.ytimg.com/vi/jNQXAC9IVRw/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgBvgKAAvABigIMCAAQARhVIFkoZTAP&rs=AOn4CLB7NY0fx4yZYDj27223V3b7Sowf5w",
          "height": 188,
          "width": 336
        }
      ],
      "timestamp": null,
      "release_timestamp": null,
      "availability": null,
      "view_count": 372000000,
      "live_status": null,
      "channel_is_verified": null,
      "__x_forwarded_for_ip": null
    }
  ],
  "extractor_key": "YoutubeTab",
  "extractor": "youtube:tab",
  "webpage_url": "https://www.youtube.com/playlist?list=UU4QobU6STFB0P71PMvOGN5A",
  "original_url": "https://www.youtube.com/playlist?list=UU4QobU6STFB0P71PMvOGN5A",
  "webpage_url_basename": "playlist",
  "webpage_url_domain": "youtube.com",
  "release_year": null,
  "epoch": 1758977670,
  "_version": {
    "version": "2025.09.26",
    "current_git_head": null,
    "release_git_head": "12b57d2858845c0c7fb33bf9aa8ed7be6905535d",
    "repository": "yt-dlp/yt-dlp"
  }
}
