=== ryn-cx/yt-dlapi/src/yt_dlapi/video/schema.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"id": {"type": "string"}, "title": {"type": "string"}, "formats": {"type": "array", "items": {"type": "object", "properties": {"asr": {"type": ["integer", "null"]}, "filesize": {"type": "integer"}, "format_id": {"type": "string"}, "format_note": {"type": "string"}, "source_preference": {"type": "integer"}, "fps": {"type": ["null", "number"]}, "audio_channels": {"type": ["integer", "null"]}, "height": {"type": ["integer", "null"]}, "quality": {"type": "number"}, "has_drm": {"type": "boolean"}, "tbr": {"type": "number"}, "filesize_approx": {"type": "integer"}, "url": {"type": "string"}, "width": {"type": ["integer", "null"]}, "language": {"type": "null"}, "language_preference": {"type": "integer"}, "preference": {"type": "null"}, "ext": {"type": "string"}, "vcodec": {"type": "string"}, "acodec": {"type": "string"}, "dynamic_range": {"type": "null"}, "available_at": {"type": "integer"}, "downloader_options": {"type": "object", "properties": {"http_chunk_size": {"type": "integer"}}, "required": ["http_chunk_size"]}, "container": {"type": "string"}, "format_index": {"type": "null"}, "manifest_url": {"type": "string"}, "protocol": {"type": "string"}}, "required": ["acodec", "available_at", "dynamic_range", "ext", "format_id", "fps", "has_drm", "height", "preference", "quality", "source_preference", "tbr", "url", "vcodec", "width"]}}, "thumbnails": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "height": {"type": "integer"}, "width": {"type": "integer"}, "preference": {"type": "integer"}}, "required": ["preference", "url"]}}, "thumbnail": {"type": "string"}, "description": {"type": "string"}, "channel_id": {"type": "string"}, "channel_url": {"type": "string"}, "duration": {"type": "integer"}, "view_count": {"type": "integer"}, "average_rating": {"type": "null"}, "age_limit": {"type": "integer"}, "webpage_url": {"type": "string"}, "categories": {"type": "array", "items": {"type": "string"}}, "tags": {"type": "array", "items": {"type": "string"}}, "playable_in_embed": {"type": "boolean"}, "live_status": {"type": "string"}, "media_type": {"type": "string"}, "release_timestamp": {"type": "null"}, "_format_sort_fields": {"type": "array", "items": {"type": "string"}}, "automatic_captions": {"type": "object", "properties": {"en": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "ext": {"type": "string"}, "protocol": {"type": "string"}, "__yt_dlp_client": {"type": "string"}}, "required": ["__yt_dlp_client", "ext", "protocol", "url"]}}, "de": {"type": "array", "items": {"type": "object", "properties": {"url": {"type": "string"}, "ext": {"type": "string"}, "protocol": {"type": "string"}, "__yt_dlp_client": {"type": "string"}}, "required": ["__yt_dlp_client", "ext", "protocol", "url"]}}}, "required": ["de", "en"]}, "subtitles": {"type": "object", "properties": {"en": {"type": "array", "items": {"type": "object", "properties": {"ext": {"type": "string"}, "url": {"type": "string"}, "name": {"type": "string"}, "impersonate": {"type": "boolean"}, "__yt_dlp_client": {"type": "string"}}, "required": ["__yt_dlp_client", "ext", "impersonate", "name", "url"]}}, "de": {"type": "array", "items": {"type": "object", "properties": {"ext": {"type": "string"}, "url": {"type": "string"}, "name": {"type": "string"}, "impersonate": {"type": "boolean"}, "__yt_dlp_client": {"type": "string"}}, "required": ["__yt_dlp_client", "ext", "impersonate", "name", "url"]}}}, "required": ["de", "en"]}, "comment_count": {"type": "integer"}, "chapters": {"type": "array", "items": {"type": "object", "properties": {"start_time": {"type": "number"}, "title": {"type": "string"}}, "required": ["start_time", "title"]}}, "heatmap": {"type": "array", "items": {"type": "object", "properties": {"start_time": {"type": "number"}, "end_time": {"type": "number"}, "value": {"type": "number"}}, "required": ["end_time", "start_time", "value"]}}, "location": {"type": "string"}, "like_count": {"type": "integer"}, "channel": {"type": "string"}, "channel_follower_count": {"type": "integer"}, "channel_is_verified": {"type": "boolean"}, "uploader": {"type": "string"}, "uploader_id": {"type": "string"}, "uploader_url": {"type": "string"}, "upload_date": {"type": "string"}, "timestamp": {"type": "integer"}, "availability": {"type": "string"}, "__post_extractor": {"type": "null"}, "original_url": {"type": "string"}, "webpage_url_basename": {"type": "string"}, "webpage_url_domain": {"type": "string"}, "extractor": {"type": "string"}, "extractor_key": {"type": "string"}, "epoch": {"type": "integer"}, "_type": {"type": "string"}, "_version": {"type": "object", "properties": {"version": {"type": "string"}, "current_git_head": {"type": "null"}, "release_git_head": {"type": "string"}, "repository": {"type": "string"}}, "required": ["current_git_head", "release_git_head", "repository", "version"]}}, "required": ["__post_extractor", "_format_sort_fields", "_type", "_version", "age_limit", "automatic_captions", "availability", "average_rating", "categories", "channel", "channel_follower_count", "channel_id", "channel_is_verified", "channel_url", "chapters", "comment_count", "description", "duration", "epoch", "extractor", "extractor_key", "formats", "heatmap", "id", "like_count", "live_status", "location", "media_type", "original_url", "playable_in_embed", "release_timestamp", "subtitles", "tags", "thumbnail", "thumbnails", "timestamp", "title", "upload_date", "uploader", "uploader_id", "uploader_url", "view_count", "webpage_url", "webpage_url_basename", "webpage_url_domain"]}

=== ryn-cx/yt-dlapi/src/yt_dlapi/_input/video/c93efa73-b1c0-40c8-a211-08b5749f9c64.json
{
  "id": "jNQXAC9IVRw",
  "title": "Me at the zoo",
  "formats": [
    {
      "asr": 44100,
      "filesize": 791367,
      "format_id": "18",
      "format_note": "240p",
      "source_preference": -1,
      "fps": 15,
      "audio_channels": 1,
      "height": 240,
      "quality": 5.0,
      "has_drm": false,
      "tbr": 332.105,
      "filesize_approx": 791364,
      "url": "https://rr1---sn-n4v7sney.googlevideo.com/videoplayback?expire=1758999516&ei=fN_XaJL2BfGty_sP94OyuQc&ip=107.204.173.81&id=o-ABpum7n35USM_9BPUowOZklfFhR1o5GSIcGjKf-k4QKT&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&cps=436&met=1758977916%2C&mh=VD&mm=31%2C29&mn=sn-n4v7sney%2Csn-o097znzk&ms=au%2Crdu&mv=m&mvi=1&pl=21&rms=au%2Cau&initcwndbps=1950000&bui=ATw7iSV9iKGFWbmwZS3OYIHMsffmzuuX7FdQ1_yTyt2ENAIylW6RozMvc95XRhOA6F8EbnV7TFOZIr4l&vprv=1&svpuc=1&mime=video%2Fmp4&ns=giEMj9abzCZzqhA5YRRkjF0Q&rqh=1&gir=yes&clen=791367&ratebypass=yes&dur=19.063&lmt=1680501259475484&mt=1758977378&fvip=3&lmw=1&fexp=51565116%2C51565682%2C51580970&c=TVHTML5&sefc=1&txp=4530434&n=ccPCnIl4TLBDtg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhANie0Ej62AO2vFO2LKAKaBeylbuK_TWS8bPZ5Inn-cdzAiBaMLu3xTTbYEw2HXXTsle1YiG3KxGS33ElhgXkTgbFZQ%3D%3D&lsparams=cps%2Cmet%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgTaMJq0BMo3iQLNoYRVw4IdUm4tSMBn9Xj39In2gjY2ACIQDrPF-PNGlT8VooPnbqxQ4wsN1-G-0Io6SFo5SRQyhl2g%3D%3D",
      "width": 320,
      "language": null,
      "language_preference": -1,
      "preference": null,
      "ext": "mp4",
      "vcodec": "avc1.42001E",
      "acodec": "mp4a.40.2",
      "dynamic_range": null,
      "available_at": 1758977922,
      "downloader_options": {
        "http_chunk_size": 10485760
      }
    },
    {
      "asr": null,
      "filesize": 432799,
      "format_id": "133",
      "format_note": "240p",
      "source_preference": -1,
      "fps": 15,
      "audio_channels": null,
      "height": 240,
      "quality": 5.0,
      "has_drm": false,
      "tbr": 182.876,
      "filesize_approx": 432798,
      "url": "https://rr1---sn-n4v7sney.googlevideo.com/videoplayback?expire=1758999516&ei=fN_XaJL2BfGty_sP94OyuQc&ip=107.204.173.81&id=o-ABpum7n35USM_9BPUowOZklfFhR1o5GSIcGjKf-k4QKT&itag=133&aitags=133%2C160%2C242%2C278%2C394%2C395&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&cps=436&met=1758977916%2C&mh=VD&mm=31%2C29&mn=sn-n4v7sney%2Csn-o097znzk&ms=au%2Crdu&mv=m&mvi=1&pl=21&rms=au%2Cau&initcwndbps=1950000&bui=ATw7iSXw0zRJMkHYEW8UvIrmQVpPI24BnW8V2s8Vkx5mdtOGY34sIWQM4xwoETS_PLztQKVhd8PVhaON&vprv=1&svpuc=1&mime=video%2Fmp4&ns=AzY7VPs9Cet4sgaZLlB1YWEQ&rqh=1&gir=yes&clen=432799&dur=18.933&lmt=1680501288781393&mt=1758977378&fvip=3&keepalive=yes&lmw=1&fexp=51565116%2C51565682%2C51580970&c=TVHTML5&sefc=1&txp=4530434&n=k7BXkZ4bQEG9Ig&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhANIXk6aynMblFSZlqNUs6dRzVCjLSyO_yDpf6P7NFS_vAiEAo5RpzlJpJlw1SAhPVj9W2dVxdWkEqU8DCTEq0YrvyWo%3D&lsparams=cps%2Cmet%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgTaMJq0BMo3iQLNoYRVw4IdUm4tSMBn9Xj39In2gjY2ACIQDrPF-PNGlT8VooPnbqxQ4wsN1-G-0Io6SFo5SRQyhl2g%3D%3D",
      "width": 320,
      "language": null,
      "language_preference": -1,
      "preference": null,
      "ext": "mp4",
      "vcodec": "avc1.4d400c",
      "acodec": "none",
      "dynamic_range": null,
      "container": "mp4_dash",
      "available_at": 1758977922,
      "downloader_options": {
        "http_chunk_size": 10485760
      }
    },
    {
      "asr": null,
      "filesize": 293080,
      "format_id": "242",
      "format_note": "240p",
      "source_preference": -1,
      "fps": 15,
      "audio_channels": null,
      "height": 240,
      "quality": 5.0,
      "has_drm": false,
      "tbr": 123.838,
      "filesize_approx": 293078,
      "url": "https://rr1---sn-n4v7sney.googlevideo.com/videoplayback?expire=1758999516&ei=fN_XaJL2BfGty_sP94OyuQc&ip=107.204.173.81&id=o-ABpum7n35USM_9BPUowOZklfFhR1o5GSIcGjKf-k4QKT&itag=242&aitags=133%2C160%2C242%2C278%2C394%2C395&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&cps=436&met=1758977916%2C&mh=VD&mm=31%2C29&mn=sn-n4v7sney%2Csn-o097znzk&ms=au%2Crdu&mv=m&mvi=1&pl=21&rms=au%2Cau&initcwndbps=1950000&bui=ATw7iSXw0zRJMkHYEW8UvIrmQVpPI24BnW8V2s8Vkx5mdtOGY34sIWQM4xwoETS_PLztQKVhd8PVhaON&vprv=1&svpuc=1&mime=video%2Fwebm&ns=AzY7VPs9Cet4sgaZLlB1YWEQ&rqh=1&gir=yes&clen=293080&dur=18.933&lmt=1680501309294787&mt=1758977378&fvip=3&keepalive=yes&lmw=1&fexp=51565116%2C51565682%2C51580970&c=TVHTML5&sefc=1&txp=4530434&n=k7BXkZ4bQEG9Ig&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgCaCI9_HUb4B4ZUYd-Vt5Ufwm8zKOj3gSSMaSFGRWC-cCIQDOWt0opKOi-qNTS-7kJzZNWR4UowX3ozPiLshtc0s8SQ%3D%3D&lsparams=cps%2Cmet%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgTaMJq0BMo3iQLNoYRVw4IdUm4tSMBn9Xj39In2gjY2ACIQDrPF-PNGlT8VooPnbqxQ4wsN1-G-0Io6SFo5SRQyhl2g%3D%3D",
      "width": 320,
      "language": null,
      "language_preference": -1,
      "preference": null,
      "ext": "webm",
      "vcodec": "vp9",
      "acodec": "none",
      "dynamic_range": null,
      "container": "webm_dash",
      "available_at": 1758977922,
      "downloader_options": {
        "http_chunk_size": 10485760
      }
    },
    {
      "asr": null,
      "filesize": 258472,
      "format_id": "395",
      "format_note": "240p",
      "source_preference": -1,
      "fps": 15,
      "audio_channels": null,
      "height": 240,
      "quality": 5.0,
      "has_drm": false,
      "tbr": 109.215,
      "filesize_approx": 258470,
      "url": "https://rr1---sn-n4v7sney.googlevideo.com/videoplayback?expire=1758999516&ei=fN_XaJL2BfGty_sP94OyuQc&ip=107.204.173.81&id=o-ABpum7n35USM_9BPUowOZklfFhR1o5GSIcGjKf-k4QKT&itag=395&aitags=133%2C160%2C242%2C278%2C394%2C395&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&cps=436&met=1758977916%2C&mh=VD&mm=31%2C29&mn=sn-n4v7sney%2Csn-o097znzk&ms=au%2Crdu&mv=m&mvi=1&pl=21&rms=au%2Cau&initcwndbps=1950000&bui=ATw7iSXw0zRJMkHYEW8UvIrmQVpPI24BnW8V2s8Vkx5mdtOGY34sIWQM4xwoETS_PLztQKVhd8PVhaON&vprv=1&svpuc=1&mime=video%2Fmp4&ns=AzY7VPs9Cet4sgaZLlB1YWEQ&rqh=1&gir=yes&clen=258472&dur=18.933&lmt=1680501372905765&mt=1758977378&fvip=3&keepalive=yes&lmw=1&fexp=51565116%2C51565682%2C51580970&c=TVHTML5&sefc=1&txp=4530434&n=k7BXkZ4bQEG9Ig&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAORRQReAKl616M1qZoDFHtZl03Q2vLqbPqrG2NsqIhwHAiEAxIeT60bqbHzP5KmX2I1HxBjZFbSSrzs57DZV2VVzwpA%3D&lsparams=cps%2Cmet%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgTaMJq0BMo3iQLNoYRVw4IdUm4tSMBn9Xj39In2gjY2ACIQDrPF-PNGlT8VooPnbqxQ4wsN1-G-0Io6SFo5SRQyhl2g%3D%3D",
      "width": 320,
      "language": null,
      "language_preference": -1,
      "preference": null,
      "ext": "mp4",
      "vcodec": "av01.0.00M.08.0.110.05.01.06.0",
      "acodec": "none",
      "dynamic_range": null,
      "container": "mp4_dash",
      "available_at": 1758977922,
      "downloader_options": {
        "http_chunk_size": 10485760
      }
    },
    {
      "asr": null,
      "filesize": 195132,
      "format_id": "160",
      "format_note": "144p",
      "source_preference": -1,
      "fps": 15,
      "audio_channels": null,
      "height": 144,
      "quality": 0.0,
      "has_drm": false,
      "tbr": 82.451,
      "filesize_approx": 195130,
      "url": "https://rr1---sn-n4v7sney.googlevideo.com/videoplayback?expire=1758999516&ei=fN_XaJL2BfGty_sP94OyuQc&ip=107.204.173.81&id=o-ABpum7n35USM_9BPUowOZklfFhR1o5GSIcGjKf-k4QKT&itag=160&aitags=133%2C160%2C242%2C278%2C394%2C395&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&cps=436&met=1758977916%2C&mh=VD&mm=31%2C29&mn=sn-n4v7sney%2Csn-o097znzk&ms=au%2Crdu&mv=m&mvi=1&pl=21&rms=au%2Cau&initcwndbps=1950000&bui=ATw7iSXw0zRJMkHYEW8UvIrmQVpPI24BnW8V2s8Vkx5mdtOGY34sIWQM4xwoETS_PLztQKVhd8PVhaON&vprv=1&svpuc=1&mime=video%2Fmp4&ns=AzY7VPs9Cet4sgaZLlB1YWEQ&rqh=1&gir=yes&clen=195132&dur=18.933&lmt=1680501287522448&mt=1758977378&fvip=3&keepalive=yes&lmw=1&fexp=51565116%2C51565682%2C51580970&c=TVHTML5&sefc=1&txp=4530434&n=k7BXkZ4bQEG9Ig&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgJRAHJC1mWMa8ACdnfd0WVMuDKGPbm4HC4gGM6eJxJKgCIGKphgF5Zzk-KOwKoyGeWumWJHpLFWr8MtyHib_3Exly&lsparams=cps%2Cmet%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgTaMJq0BMo3iQLNoYRVw4IdUm4tSMBn9Xj39In2gjY2ACIQDrPF-PNGlT8VooPnbqxQ4wsN1-G-0Io6SFo5SRQyhl2g%3D%3D",
      "width": 192,
      "language": null,
      "language_preference": -1,
      "preference": null,
      "ext": "mp4",
      "vcodec": "avc1.4d400b",
      "acodec": "none",
      "dynamic_range": null,
      "container": "mp4_dash",
      "available_at": 1758977922,
      "downloader_options": {
        "http_chunk_size": 10485760
      }
    },
    {
      "asr": null,
      "filesize": 185292,
      "format_id": "278",
      "format_note": "144p",
      "source_preference": -1,
      "fps": 15,
      "audio_channels": null,
      "height": 144,
      "quality": 0.0,
      "has_drm": false,
      "tbr": 78.293,
      "filesize_approx": 185290,
